#!/usr/bin/env python3
"""Generate a facility.json from the flow UUIDs the quickstart actually discovered.

The problem (review R2): the UI / backend read flow UUIDs from config/facility.json
(this lab's FIXED ids), but every fresh quickstart gets DIFFERENT UUIDs from the CBC
containers. So on a stranger's box the manifest's ids don't exist, and every cut
returns "source not attached". Fix: after quickstart discovers the real UUIDs via
`mxl-info -l`, write them into a manifest the control UI reads (MXL_FACILITY_JSON),
so the UI's slots and cuts match the running facility.

Usage:
    mxl-info -d /mxl-domain -l | python3 tools/facility_from_discovery.py > facility.json
    # or
    python3 tools/facility_from_discovery.py --from FILE [--vm 127.0.0.1] > facility.json

Only the labels the quickstart writers set are mapped. A label that isn't present is
simply omitted from the layout, so the UI shows only slots that actually exist.
"""
import json
import re
import sys

# mxl-info prints one line per flow:  "\tVideo : <uuid> - <label>"
_FLOW_RE = re.compile(r'^\s+(?:Video|Audio)\s*:\s*([0-9a-f-]{36})\s*-\s*(.+?)\s*$')

# The quickstart's writer labels -> facility roles. NOTE the role naming here is the
# CORRECT mapping (review R3 found the live lab's manifest had these backwards):
#   "Pattern Video" is the TEST GENERATOR's output  -> role `pattern`
#   "Clip Video"    is the FILE PLAYER's output      -> role `playout`
# plus the program-chain flows the routes look up by role (selector, keyer).
LABEL_TO_ROLE = {
    'Pattern Video': ('pattern', 'Pattern'),
    'Clip Video':    ('playout', 'Playout'),
    'Selector PGM':  ('selector', 'Selector PGM'),
    'Keyer PGM':     ('keyer', 'Keyer PGM'),
    # cameras / guests appear only if their writers are running:
    'CAM 1 Live':    ('cam', 'Studio Cam 1'),
    'CAM 2 Live':    ('cam2', 'Studio Cam 2'),
    'Guest 1 Video': ('guest1', 'Guest 1'),
    'Guest 2 Video': ('guest2', 'Guest 2'),
    'Layout PGM':    ('layout', 'Layout'),
}
# which roles are selectable SOURCES (appear as multiview tiles / cut targets),
# in the order the UI should show them. selector/keyer are plumbing, not tiles.
SOURCE_ROLE_ORDER = ['cam', 'playout', 'pattern', 'cam2', 'guest1', 'guest2', 'layout']


def parse_flows(text):
    """label -> uuid (first wins). Video and Audio lines both carry labels."""
    flows = {}
    for line in text.splitlines():
        m = _FLOW_RE.match(line)
        if m:
            uuid, label = m.group(1), m.group(2)
            flows.setdefault(label, uuid)
    return flows


def build_manifest(flows, vm='127.0.0.1'):
    # role -> {uuid, label}
    video_flows = {}
    for label, uuid in flows.items():
        if label in LABEL_TO_ROLE:
            role, nice = LABEL_TO_ROLE[label]
            video_flows[role] = {'uuid': uuid, 'label': nice}

    # layout = the source roles that actually exist, in the canonical order
    present_sources = [r for r in SOURCE_ROLE_ORDER if r in video_flows]
    labels = [video_flows[r]['label'] for r in present_sources]

    manifest = {
        '_comment': 'Generated by tools/facility_from_discovery.py from a live quickstart. '
                    'UUIDs are this box\'s discovered flows, not the lab defaults.',
        'facility': {
            'name': 'MXL Quickstart',
            'domain_path': '/mxl-domain',
            'resolution': '1920x1080',
            'framerate': '30',
        },
        'network': {'mxl_vm': vm},
        'video_flows': video_flows,
        'audio_flows': {},
        'program': {
            'selector_inputs': present_sources,
            'layout_inputs': present_sources,
            'layout_input_labels': labels,
        },
    }
    return manifest


def main(argv):
    src = None
    vm = '127.0.0.1'
    i = 1
    while i < len(argv):
        a = argv[i]
        if a == '--from':
            src = open(argv[i + 1]).read(); i += 2
        elif a == '--vm':
            vm = argv[i + 1]; i += 2
        else:
            sys.stderr.write(f'unknown arg: {a}\n'); return 2
    if src is None:
        src = sys.stdin.read()
    flows = parse_flows(src)
    if not flows:
        sys.stderr.write('facility_from_discovery: no flows found in input\n')
        return 1
    manifest = build_manifest(flows, vm)
    if not manifest['program']['layout_inputs']:
        sys.stderr.write('facility_from_discovery: no known source labels found — '
                         'is the quickstart running? (looked for Pattern/Clip Video etc.)\n')
        return 1
    json.dump(manifest, sys.stdout, indent=2)
    sys.stdout.write('\n')
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
